config/routes.rb
Taller::Application.routes.draw do
  
  get "main/index"

  match 'nuevacita/:placa/:fecha/:hora' => 'main#create_cita'
  match 'consultarfechahora/:fecha/:hora(.:format)' => 'main#find_cita'
  match 'consultarfecha/:fecha(.:format)' => 'main#find_cita'

  match 'recibirvehiculo/:cita_id(.:format)' => 'main#create_orden'
  match 'agregarservicio/:orden_id/:servicio_id(.:format)' => 'main#create_servicio'

  match 'servicio_nombre/:servicio_id(.:format)' => 'testdata#servicio_nombre'
  

end

app/models/cita.rb
class Cita < ActiveRecord::Base
  belongs_to :vehiculo
  belongs_to :orden
  has_many :citas  
  validates :fecha, :hora, :cliente_id, :estados_id, :presence => true

  validates_uniqueness_of :fecha, :scope => :hora, :message => "Ya existe una cita con ese horario."
  
end

app/controllers/citas_controller.rb
class CitasController < ApplicationController
  
  def index
    @citas = Cita.find :all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @citas }
    end
  end

  def show
    @cita = Cita.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cita }
    end
  end

  def new
    @cita = Cita.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cita }
    end
  end

  def edit
    @cita = Cita.find(params[:id])
  end

  def create
    @cita = Cita.new(params[:cita])
    
    respond_to do |format|
      if @cita.save
        flash[:notice] = 'Cita was successfully created.'
        format.html { redirect_to(@cita) }
        format.xml  { render :xml => @cita, :status => :created, :location => @cita }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cita.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @cita = Cita.find(params[:id])
    
    respond_to do |format|
      if @cita.update_attributes(params[:cita])
        flash[:notice] = 'Cita was successfully updated.'
        format.html { redirect_to(@cita) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cita.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @cita = Cita.find(params[:id])
    @cita.destroy
    
    respond_to do |format|
      format.html { redirect_to(citas_url) }
      format.xml  { head :ok }
    end
  end

  

end

app/helpers/citas_helper.rb
module CitasHelper
end

app/views/citas/_form.html.erb
<%= form_for(@cita) do |f| %>
  <% if @cita.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cita.errors.count, "error") %> prohibited this cita from being saved:</h2>

      <ul>
      <% @cita.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :hora %><br />
    <%= f.text_field :hora %>
  </div>
  <div class="field">
    <%= f.label :cliente_id %><br />
    <%= f.text_field :cliente_id %>
  </div>
  <div class="field">
    <%= f.label :estados_id %><br />
    <%= f.text_field :estados_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/citas/edit.html.erb
<h1>Editing cita</h1>

<%= render 'form' %>

<%= link_to 'Show', @cita %> |
<%= link_to 'Back', citas_path %>

app/views/citas/index.html.erb
<h1>Listing citas</h1>

<table>
  <tr>
    <th>Fecha</th>
    <th>Hora</th>
    <th>Cliente</th>
    <th>Estados</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @citas.each do |cita| %>
  <tr>
    <td><%= cita.fecha %></td>
    <td><%= cita.hora %></td>
    <td><%= cita.cliente_id %></td>
    <td><%= cita.estados_id %></td>
    <td><%= link_to 'Show', cita %></td>
    <td><%= link_to 'Edit', edit_cita_path(cita) %></td>
    <td><%= link_to 'Destroy', cita, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cita', new_cita_path %>

app/views/citas/new.html.erb
<h1>New cita</h1>

<%= render 'form' %>

<%= link_to 'Back', citas_path %>

app/views/citas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fecha:</b>
  <%= @cita.fecha %>
</p>

<p>
  <b>Hora:</b>
  <%= @cita.hora %>
</p>

<p>
  <b>Cliente:</b>
  <%= @cita.cliente_id %>
</p>

<p>
  <b>Estados:</b>
  <%= @cita.estados_id %>
</p>


<%= link_to 'Edit', edit_cita_path(@cita) %> |
<%= link_to 'Back', citas_path %>