config/routes.rb
Taller::Application.routes.draw do
  
  get "main/index"

  match 'nuevacita/:placa/:fecha/:hora' => 'main#create_cita'
  match 'consultarfechahora/:fecha/:hora(.:format)' => 'main#find_cita'
  match 'consultarfecha/:fecha(.:format)' => 'main#find_cita'

  match 'recibirvehiculo/:cita_id(.:format)' => 'main#create_orden'
  match 'agregarservicio/:orden_id/:servicio_id(.:format)' => 'main#create_servicio'

  match 'servicio_nombre/:servicio_id(.:format)' => 'testdata#servicio_nombre'
  

end

app/controllers/ordenes_controller.rb
class OrdenesController < ApplicationController
  # GET /ordenes
  # GET /ordenes.xml
  def index
    @ordenes = Orden.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ordenes }
    end
  end

  # GET /ordenes/1
  # GET /ordenes/1.xml
  def show
    @orden = Orden.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @orden }
    end
  end

  # GET /ordenes/new
  # GET /ordenes/new.xml
  def new
    @orden = Orden.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @orden }
    end
  end

  # GET /ordenes/1/edit
  def edit
    @orden = Orden.find(params[:id])
  end

  # POST /ordenes
  # POST /ordenes.xml
  def create
    @orden = Orden.new(params[:orden])

    respond_to do |format|
      if @orden.save
        format.html { redirect_to(@orden, :notice => 'Orden was successfully created.') }
        format.xml  { render :xml => @orden, :status => :created, :location => @orden }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @orden.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ordenes/1
  # PUT /ordenes/1.xml
  def update
    @orden = Orden.find(params[:id])

    respond_to do |format|
      if @orden.update_attributes(params[:orden])
        format.html { redirect_to(@orden, :notice => 'Orden was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @orden.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ordenes/1
  # DELETE /ordenes/1.xml
  def destroy
    @orden = Orden.find(params[:id])
    @orden.destroy

    respond_to do |format|
      format.html { redirect_to(ordenes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ordenes_helper.rb
module OrdenesHelper
end

app/views/ordenes/_form.html.erb
<%= form_for(@orden) do |f| %>
  <% if @orden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orden.errors.count, "error") %> prohibited this orden from being saved:</h2>

      <ul>
      <% @orden.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cita_id %><br />
    <%= f.text_field :cita_id %>
  </div>
  <div class="field">
    <%= f.label :estado_id %><br />
    <%= f.text_field :estado_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ordenes/edit.html.erb
<h1>Editing orden</h1>

<%= render 'form' %>

<%= link_to 'Show', @orden %> |
<%= link_to 'Back', ordenes_path %>

app/views/ordenes/index.html.erb
<h1>Listing ordenes</h1>

<table>
  <tr>
    <th>Cita</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ordenes.each do |orden| %>
  <tr>
    <td><%= orden.cita_id %></td>
    <td><%= orden.estado_id %></td>
    <td><%= link_to 'Show', orden %></td>
    <td><%= link_to 'Edit', edit_orden_path(orden) %></td>
    <td><%= link_to 'Destroy', orden, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Orden', new_orden_path %>

app/views/ordenes/new.html.erb
<h1>New orden</h1>

<%= render 'form' %>

<%= link_to 'Back', ordenes_path %>

app/views/ordenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cita:</b>
  <%= @orden.cita_id %>
</p>

<p>
  <b>Estado:</b>
  <%= @orden.estado_id %>
</p>


<%= link_to 'Edit', edit_orden_path(@orden) %> |
<%= link_to 'Back', ordenes_path %>